### PR TITLE
Added encrypted binstar token

### PR DESCRIPTION
**Pull request by danielparton**

### CODE REVIEW

**Comment by jchodera** [comment]
I don't think you want your `secure` line to be commented out:
```
    # secure: "eA8N3FhgO03HN7mJGwR0iLtIsgFufi1wYMr1I//x7NLhhqrZvdbmo6ukecjgmz32fq3JHJM5qtcEr1+kp411VG9rCCGeeL8WBfxscIwxUIPaTDkIulFY/tKeEn+nObHscEtKyS9aPxImthwKEtmbgxdysYXOS1nnUBXSC5FEfW/exsG04AddBS85UDcQAY96jBb3TcNSuAZnHVZKkRPFnwTVuKV9eU/KLFDXfjeJodntaRY5YpuR4Njsm6FXHKqQgprbSnXe8o3+zN+XAHRCcyRgqFzbiquyhFnTUYd+6dwOFNwTtUGhEiEUyfCcb9Z/vUahT7RK5Vflb/c0kKK5nmrcwQT3Ykc6Jhb5Por3H/Ue1fnXz87+YsiX3BzDNANnDx2vt85GX/UHT9l8jkgwfw9tJgSGDIIjBaHAnVzw1kzAHRi0Kb5TkXHaPIdaM7CvOae6KxPk+OA6sg6j0lU0AW0vCQNR1UVkbmyaftCUTUjX/L2SJNVQT2LGh6qb3GeH23WrF32BO4nBLUeQWWcvldHHGaOlyEo8NeZgfHsluiNLe8b6aVE6li02F9KLnFLarxkCPOUcBmS3AHtz0aRig0CNEywE2fhYz7jrgq3WLuBHCF9lFZA4l4u1jUB14WVxt+TUNwz0rmX40fgoslSsJKgo+QGjg0hT0WfZg7ndpKk="

```

**Comment by danielparton** [comment]
True, thanks :)

**Comment by jchodera** [comment]
Which packages are we still relying on the `dannyparton` binstar repo for?
```
conda config --add channels https://conda.anaconda.org/dannyparton
```

**Comment by danielparton** [comment]
TargetExplorer requires the flask-sqlalchemy extension - I added a recipe on choderalab/conda-recipes, but that won't be available until Jenkins etc is set up.

In the mean time, I was going to upload binaries on my own binstar channel. I can remove that channel from `install.sh` once flask-sqlalchemy is available via the choderalab channel.

**Comment by jchodera** [comment]
OK, I almost have Jenkins working for choderalab.  Will let you know when it works.

**Comment by danielparton** [comment]
So the flask-sqlalchemy dependency is installing fine now it is available on the choderalab conda channel. Unfortunately Oncotator seems to be down at the moment (see screen grab below), causing a couple of the tests to fail with the following exception.
```
HTTPError: HTTP Error 503: Service Temporarily Unavailable
```

screen shot 2015-07-14 at 11 50 21 pm

It's inevitable that tests which rely on external resources will result in this kind of difficulty.
But I think it should be fairly easy to implement exception handling in the tests to deal with this specific situation.

**Comment by danielparton** [comment]
Example code for handling this:

```.py
from urllib2 import HTTPError
from nose import SkipTest

def test_gather_cbioportal():
    with projecttest_context(set_up_project_stage='uniprot'):
        try:
            GatherCbioportalData()
        except HTTPError as e:
            if e.code == 503:
                raise SkipTest(e.reason)
            else:
                raise
```

And this is the description of the 503 HTTP code from w3.org:

> 10.5.4 503 Service Unavailable
> 
> The server is currently unable to handle the request due to a temporary overloading or maintenance of the server. The implication is that this is a temporary condition which will be alleviated after some delay. If known, the length of the delay MAY be indicated in a Retry-After header. If no Retry-After is given, the client SHOULD handle the response as it would for a 500 response.

> ```
Note: The existence of the 503 status code does not imply that a
      server must use it when becoming overloaded. Some servers may wish
      to simply refuse the connection.
```

Will need to think whether we actually want to skip tests in this situation.

Might be better to just consider any test with external dependencies to be an "integration test" rather than a unit test, and avoid making CI dependent upon them. Such tests could be labeled with an "integration" attribute decorator. And these could perhaps be run at the end of the `after_success.sh` script, just to provide the developer with that info, but without making Travis (and `dev` builds) dependent upon them passing.

**Pull request merged**
